name: NouveauEnchanting
version: '${project.version}'
main: net.cozycosmos.newenchanting.Main
authors: [Miden]
softdepend: [ItemsAdder,Oraxen,ExcellentEnchants,Zenchantments,AdvancedEnchantments]
api-version: 1.18
description: A new, customizable enchanting system for your server!

commands:
  nouveauenchanting:
    usage: /ne
    aliases: [ne]

permissions:
  nouveauenchanting.command.enchant:
    default: op
    description: Grants permission to use /ne enchant